### ISSUE TITLE
Failed to create subscription : field 'external_key' doesn't have a default value

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui-standalone#23]
Its is possible that as we added the subscription external key, something got broken inside of KAUI.

_To be checked if this is still valid_

**Comment by tungleduyxyz** [comment]
Hi @pierre, is this ticket available to pick up?
I see it's still **To be checked** 4 years ago.
And don't really understand the description.

**Comment by tungleduyxyz** [comment]
`Regarding https://github.com/killbill/killbill-admin-ui-standalone/issues/23, I agree, the ticket isn't great :slightly_smiling_face:
A while back, we had added the ability in Kill Bill to specify an external key on the subscription object, upon creation (external key is a unique identifier that the customer can specify, by default we set the external key to the subscription id). It looks like there was a related bug in Kaui when we did that.
So the task is:
1. If we can specify the subscription external key (as well as the bundle external key) when we create a subscription (not sure if the UI supports it yet), verify that we can specify it. You can do 4 manual tests (and if it works, close the ticket):
Specify bundle external key, don't specify subscription external key, verify it works
Specify bundle external key, specify subscription external key, verify it works
Don't specify bundle external key, specify subscription external key, verify it works
Don't specify bundle external key, don't specify subscription external key, verify it works
2. If we don't support specifying the subscription external key in the UI yet, we should add the functionality (and then do the above tests)
Hope this helps :slightly_smiling_face:`

**Comment by tungleduyxyz** [comment]
Hi I believe that the **bundle external key** and **subscription external key** you mentioned above are Bundle Key and Subscription Key in the UI.
![image](https://github.com/killbill/killbill-admin-ui-standalone/assets/80109474/f8de31cd-963f-4f46-b20f-fc0d5f55743c)
Here is the result for the test cases:
1. Specify bundle external key, don't specify subscription external key, verify it works :white_check_mark:
-> Subscription data: `@bundle_id="1eaf166d-1d67-421c-ba65-a73d23335b74", @bundle_external_key="bundlekey", @subscription_id="99e8a6ff-fcf2-4793-b243-e4a0ec9f9cf8", @external_key="99e8a6ff-fcf2-4793-b243-e4a0ec9f9cf8"`

2. Specify bundle external key, specify subscription external key, verify it works :white_check_mark:
-> Subscription data:  `@bundle_id="9f034493-f7c4-4161-a708-a51b557c9c6c", @bundle_external_key="bundlekey2", @subscription_id="0c005342-a800-4216-87ff-722351e51841", @external_key="subscriptionkey2"`

3. Don't specify bundle external key, specify subscription external key, verify it works :white_check_mark:
-> Subscription data:  `@bundle_id="2074b18d-4f10-42db-8043-40a1295693c0", @bundle_external_key="2074b18d-4f10-42db-8043-40a1295693c0", @subscription_id="d0e97fb9-54f8-4ce7-b81f-b2e5c54d5fcb", @external_key="subscriptionkey3"`

4. Don't specify bundle external key, don't specify subscription external key, verify it works :white_check_mark:
->  Subscription data:  `@bundle_id="65e96113-6e38-4854-ba14-7ca2bb970515", @bundle_external_key="65e96113-6e38-4854-ba14-7ca2bb970515", @subscription_id="0551bd4c-45dd-4eaa-a145-fc6a6dbac868", @external_key="0551bd4c-45dd-4eaa-a145-fc6a6dbac868"`
