### ISSUE TITLE
Inconsistencies in our plugin_name naming convention

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui-standalone#31]
_Verify if this is still valid by installing the latest payment-test plugin and verifying Kaui behaves as expected (custom screen accessible via the menu at the top)_

For the payment test plugin, our [code expects](https://github.com/killbill/killbill-admin-ui-standalone/blob/master/app/controllers/main_controller.rb#L34) `killbill-payment-test`, but instead we return:

```
     {
        "bundleSymbolicName": "org.kill-bill.billing.plugin.java.payment-test-plugin",
        "pluginKey": "payment-test",
        "pluginName": "payment-test-plugin",
        "version": "7.0.4",
        "state": "RUNNING",
        "isSelectedForStart": true,
        "services": [
          {
            "serviceTypeName": "javax.servlet.Servlet",
            "registrationName": "killbill-payment-test"
          },
          {
            "serviceTypeName": "org.killbill.billing.payment.plugin.api.PaymentPluginApi",
            "registrationName": "killbill-payment-test"
          }
        ]
      }
```

**Comment by tungleduyxyz** [comment]
Hi @pierre, I don't really understand the expectation of this ticket.
But I see this commit was created 4 months after this ticket and already updated **killbill-payment-test** to **payment-test-plugin**
