### ISSUE TITLE
common.less wasn't found 

### ISSUE THREAD

**Issue by Shwethac999** [killbill/killbill-admin-ui-standalone#42]
When I try to run the command "rails s" after " bundle install" I am facing "Rhino::Ruby::Exception: [object RuntimeError] common.less wasnt found" please find attached file for error reference 
my Kaui-standalone version is 2.0.9, JRuby-9.3.0.0 and my window version is windows 10
[error.txt](https://github.com/killbill/killbill-admin-ui-standalone/files/7267269/error.txt)

**Comment by pierre** [comment]
There is no `less` dependency anymore: https://github.com/killbill/killbill-admin-ui/issues/323.
