### ISSUE TITLE
Application Healthcheck

### ISSUE THREAD

**Issue by SimonWoidig** [killbill/killbill-admin-ui-standalone#66]
I was wondering, if there is some kind of an endpoint/command (`/healthz`, `/up`) I can run to get the health of the application. 
If not, could it be implemented? It would be handy for Kubernetes monitoring via probes.

Reference:
https://edgeapi.rubyonrails.org/classes/Rails/HealthController.html

**Comment by pierre** [comment]
I'm supportive. We've historically just used `/users/sign_in` but having a real healthcheck makes a lot of sense. Would you be able to submit a PR?

**Comment by SimonWoidig** [comment]
I am afraid not. I am not really experienced in Ruby.

**Comment by SimonWoidig** [comment]
Also would be nice, if the healthcheck contained the status of the connected killbill instance. But I guess it is not 100% required, since we can get the status from the killbill instance itself.

**Comment by pierre** [comment]
The healthcheck could also return the current Kaui version.

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-admin-ui-standalone/pull/75.

![image](https://github.com/killbill/killbill-admin-ui-standalone/assets/51940/b835098e-82b4-4c0a-a717-da283cda97eb)
